<table class="form-list">
    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/clearapc/index')?>')" type="button" class="scalable">
                <span><?php echo Mage::helper('adminhtml')->__('Flush APC Cache') ?></span>
            </button>
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('adminhtml')->__('APC user and system cache.')?>
        </td>
    </tr>
</table>
